### ISSUE TITLE
[mobile] Dictionary entry extends outside the flashcard for long entries

### ISSUE THREAD

**Issue by Monpocchi** [kanji-koohii/kanji-koohii#127]
<img src="https://user-images.githubusercontent.com/6685488/31562625-6f2abee8-b05c-11e7-950e-1fb6c0a4292e.png" height="400"/>

During review (here Spaced Repetition), if a flashcard with a long dictionary entry appears, the text extends outside the flash card container. In some cases, the buttons below may get covered by it completely, so that they cannot register click events, i.e. unable to proceed with review.

Used device model was Nexus 5X (Android 8.0.0), page was viewed with Firefox Beta (57.0b7)

**Comment by fabd** [comment]
Hmm that is quite frustrating as I thought I fixed this.

In the meantime two options to increase vertical space:

1. Add to homescreen. I 'm  told it works well on Android. 

2. If it works like iOS Safari, as you scroll down the address bar may disappear off the top , then when you answer and move to next card it should resize itself to fit in the available space.

**Comment by fabd** [comment]
Are you sure that's a Nexus 5X ? My preview in Google Chrome dev tools has a different scale for Nexus 5X. It sounds like you may have some kind of zoom on?

**Comment by Monpocchi** [comment]
> Are you sure that's a Nexus 5X ?

Yes, I checked the system info to make sure.
<img src="https://user-images.githubusercontent.com/6685488/31567361-6a774f34-b06f-11e7-8205-e4a1a90264f0.png" height="400"/>

> It sounds like you may have some kind of zoom on?

After you mentioned it, I was checking the system display configuration and you are right, the display size was set on "bigger". I did not remember setting this option. Sorry for the false alarm.

**Comment by fabd** [comment]
No false alarm. I suppose technically it should work but at some point it's getting difficult to fit everything in (as the flashcard becomes nearly square in the first screenshot).

Glad to hear it's working. That said if some elements feel a little too small or too big, let me know I can maek some tweaks. This is what I see in dev tools for Nexus 5X to give an idea of expected scale:

![nexus5x](https://user-images.githubusercontent.com/169391/31569300-21489cea-b07a-11e7-8076-fa45374d0e52.png)
