### ISSUE TITLE
Improve Sign Up (mostly for mobile)

### ISSUE THREAD

**Issue by fabd** [kanji-koohii/kanji-koohii#48]
There is no highlight of the wrong / missing form fields.

On mobile it's an issue because the form fills the screen and the red box with the errors at the top is not super obvious (it seems non english users in particular have trouble with this, as they don't understand the message which is not visually connected to the corresponding input, especially "Invalid answer to the security question").

**Solutions**

- add an error state to the form fields, use Bootstrap `.has-error`
- display the error message below the concerned input (new class `has-error-msg`)
- on page load focus the first invalid fiel, *this should scroll on mobile to put the field in view*

**Comment by faneca** [comment]
Also using js to scroll to the wrong form field's label's position would be a plus

**Comment by fabd** [comment]
Before

![improve-signup-before](https://user-images.githubusercontent.com/169391/31309830-1462eb94-ab8d-11e7-96ff-f16002ed6124.png)

After

![improve-signup-after](https://user-images.githubusercontent.com/169391/31309831-176854a0-ab8d-11e7-9bc1-753ab89850b4.png)
